package enums;

public enum State
{
    HINT_MENU,

    CHECK_GAME_HAS_FINISHED,
    CHECK_INFO,
    SHOW_RANKING,
    CLOSE_PROGRAM,
    CLOSE_PROGRAM_WARNING,
    CONTINUE_GAME,

    EDIT_USER,
    EXIT_CURRENT_GAME,
    EXIT_CURRENT_GAME_WARNING,

    GAME_MODE_SELECTION_MENU,
    GAME_OVER_MENU,
    GAME_PAUSE_MENU,

    INIT_PROGRAM,
    INIT_SESSION_MENU,

    LAST_ACTIONS,
    LOAD_GAME,
    LOAD_GAME_MENU,
    LOAD_RANKING,
    LOAD_SAVED_GAMES_LIST,
    LOG_IN_MENU,
    LOG_IN_USER,
    LOG_OUT_WARNING,

    MAIN_GAME_MENU,

    NEW_GAME,

    PLAY_TURN,
    PLAY_CODE_BREAKER,
    PLAY_CODE_MAKER,

    REGISTER_MENU,
    REGISTER_USER,
    RESTART_GAME,

    SAVE_GAME,
}